[package]
name = "hello_plot_max"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
log4rs = "1.2.0"
prettytable-rs = "0.10.0"
serde =  {version="1.0.159",features = ["derive"]}
serde_json = "1.0.95"
tokio = {version="1.27.0",features = ["full"]}
